DROP TABLE SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT CASCADE CONSTRAINTS;

CREATE TABLE SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT
(
  SCHEMEGROUPID           VARCHAR2(20 BYTE),
  OWNERTYPE               VARCHAR2(20 BYTE),
  OWNERNAME               VARCHAR2(300 BYTE),
  SALESCONSULTANTNAME     VARCHAR2(300 BYTE),
  EFFECTIVEFROMDATE       VARCHAR2(100 BYTE),
  EFFECTIVETODATE         VARCHAR2(100 BYTE),
  LAPSERISK               VARCHAR2(30 BYTE),
  CHANNEL                 VARCHAR2(100 BYTE),
  BUSINESSTYPE            VARCHAR2(100 BYTE),
  LAPSEREASONCATEGORY     VARCHAR2(100 BYTE),
  LAPSEREASONSUBCATEGORY  VARCHAR2(100 BYTE),
  POLICYNUMBER            VARCHAR2(100 BYTE),
  OPPORTUNITY             VARCHAR2(100 BYTE),
  LOSTREASON              VARCHAR2(100 BYTE),
  LOSTREASONCATEGORY      VARCHAR2(100 BYTE),
  NOOFEMPLOYEES           NUMBER,
  ACCOUNTNAME             VARCHAR2(300 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY IT_MI_TEAM_SF_ADC_DATA
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY "\r\n"
         SKIP 1 
         LOGFILE IT_MI_TEAM_SF_ADC_DATA: 'accountHistoryExtract.log'
         BADFILE IT_MI_TEAM_SF_ADC_DATA: 'accountHistoryExtract.bad'
         NODISCARDFILE
         FIELDS TERMINATED BY ','
         OPTIONALLY ENCLOSED BY '"'
         LRTRIM
         MISSING FIELD VALUES ARE NULL
       )
     LOCATION (IT_MI_TEAM_SF_ADC_DATA:'accountHistoryExtract.csv')
  )
REJECT LIMIT 1
NOPARALLEL
NOMONITORING;


GRANT SELECT ON SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT TO CONTROL_RO;

GRANT SELECT ON SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT TO IDT;

GRANT SELECT ON SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT TO SALES_MI;

GRANT SELECT ON SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT TO SHDEV;

GRANT SELECT ON SH_REPORTS.SAL_ACCOUNTHISTORY_EXTT TO TABMAN;
