BEGIN
    FOR i IN ( SELECT column_value
               FROM   TABLE(varchar2_ntt
                                        (
                                        'ACTIVE_INSTANCE_COUNT' , 
                                        'ALL_STREAMS_STMT_HANDLERS' , 
                                        'ALL_STREAMS_STMTS' , 
                                        'COMPUTE STATISTICS' , 
                                        'ESTIMATE STATISTICS' , 
                                        'BACKGROUND_DUMP_DEST' , 
                                        'BUFFER_POOL_KEEP' , 
                                        'BUFFER_POOL_RECYCLE' , 
                                        'COMMIT_WRITE' , 
                                        'COMPUTE_STATISTICS' , 
                                        'CORE_DUMP_DEST' , 
                                        'CSX:ENCODINGTYPE' , 
                                        'CURSOR_SHARING = SIMILAR' , 
                                        'CURSOR_SPACE_FOR_TIME' , 
                                        'DBA_COMPARISON_SCAN_SUMMARY' , 
                                        'DBLINK_ENCRYPT_LOGIN' , 
                                        'DBMS_XDB_ADMIN.CREATEREPOSITORYXMLINDEX' , 
                                        'DBMS_XDB_ADMIN.DROPREPOSITORYXMLINDEX' , 
                                        'DBMS_XDB_ADMIN.XMLINDEXADDPATH' , 
                                        'DBMS_XDB_ADMIN.XMLINDEXREMOVEPATH' , 
                                        'DDL_WAIT_FOR_LOCKS' , 
                                        'DICTIONARY-MANAGED TABLESPACES' , 
                                        'DRS_START' , 
                                        'ENQUEUE_RESOURCES' , 
                                        'GC_FILES_TO_LOCKS' , 
                                        'GLOBAL_CONTEXT_POOL_SIZE' , 
                                        'HASH_JOIN_ENABLED' , 
                                        'INSTANCE_GROUPS' , 
                                        'JOB_QUEUE_PROCESS' , 
                                        'LOCK_NAME_SPACE' , 
                                        'LOG_ARCHIVE_DEST_N' , 
                                        'LOG_ARCHIVE_DEST_STATE_N' , 
                                        'LOG_ARCHIVE_LOCAL_FIRST' , 
                                        'LOG_ARCHIVE_START' , 
                                        'LOG_PARALLELISM' , 
                                        'LOGMNR_MAX_PERSISTENT_SESSIONS' , 
                                        'MAX_COMMIT_PROPAGATION_DELAY' , 
                                        'MAX_ENABLED_ROLES' , 
                                        'MAX_JOB_SLAVE_PROCESSES' , 
                                        'MAX_ROLLBACK_SEGMENTS' , 
                                        'MOVEXDB_TABLESPACE' , 
                                        'MTS_CIRCUITS' , 
                                        'MTS_DISPATCHERS' , 
                                        'MTS_LISTENER_ADDRESS' , 
                                        'MTS_MAX_DISPATCHERS' , 
                                        'MTS_MAX_SERVERS' , 
                                        'MTS_MULTIPLE_LISTENERS' , 
                                        'MTS_SERVERS' , 
                                        'MTS_SERVICE' , 
                                        'MTS_SESSIONS' , 
                                        'OPTIMIZER_MAX_PERMUTATIONS' , 
                                        'ORACE_TRACE_COLLECTION_NAME' , 
                                        'ORACE_TRACE_COLLECTION_PATH' , 
                                        'ORACE_TRACE_COLLECTION_SIZE' , 
                                        'ORACLE ENTERPRISE MANAGER DATABASE CONTROL' , 
                                        'ORACLE_TRACE_ENABLE' , 
                                        'ORACLE_TRACE_FACILITY_NAME' , 
                                        'ORACLE_TRACE_FACILITY_PATH' , 
                                        'PARALLEL_AUTOMATIC_TUNING' , 
                                        'PARALLEL_IO_CAP_ENABLED' , 
                                        'PARTITION_VIEW_ENABLED' , 
                                        'PLSQL_COMPILER_FLAGS' , 
                                        'PLSQL_DEBUG' , 
                                        'PLSQL_NATIVE_C_COMPILER' , 
                                        'PLSQL_NATIVE_LIBRARY_DIR' , 
                                        'PLSQL_NATIVE_LIBRARY_SUBDIR_COUNT' , 
                                        'PLSQL_NATIVE_LINKER' , 
                                        'PLSQL_NATIVE_MAKE_FILE_NAME' , 
                                        'PLSQL_NATIVE_MAKE_UTILITY' , 
                                        'PLSQL_OPTIMIZE_LEVEL' , 
                                        'PLSQL_V2_COMPATIBILITY' , 
                                        'REBUILDHIERARCHICALINDEX' , 
                                        'REMOTE_ARCHIVE_ENABLE' , 
                                        'REMOTE_OS_AUTHENT' , 
                                        'RESOURCE_MANAGER_CPU_ALLOCATION' , 
                                        'ROW_LOCKING' , 
                                        'SERIAL_REUSE' , 
                                        'SERIALIZABLE' , 
                                        'SKIP_UNUSABLE_INDEXES' , 
                                        'SNMP IN ORACLE NET LISTENER' , 
                                        'SQL_PROFILES' , 
                                        'SQL_TRACE' , 
                                        'SQL_VERSION' , 
                                        'STANDBY_ARCHIVE_DEST' , 
                                        'STORED_OUTLINES' , 
                                        'TRANSACTION_AUDITING' , 
                                        'TRANSACTION_LAG' , 
                                        'UNDO_SUPPRESS_ERRORS' , 
                                        'USER_COMPARISON_SCAN_SUMMARY' , 
                                        'USER_DUMP_DEST' , 
                                        'V$FLASH_RECOVERY_AREA_USAGE' , 
                                        'XMLINDEX INDEX ON CLOB PORTIONS OF HYBRID XMLTYPE STORAGE'
                                        )
                           )
             )
    LOOP
        FOR j in ( SELECT DISTINCT owner||'.'||name var FROM all_source WHERE UPPER(text) LIKE '%'||i.column_value||'%' )
        LOOP
            dbms_output.put_line(j.var||' : '||i.column_value);                
        END LOOP;
    END LOOP;
END;




